# tomcat端口号配置
server:
  port: 80

# spring相关配置
spring:
  # 数据库配置：url、账号、密码、连接池（druid）等
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/springboot_druid_mybatisplus_demo?serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

    # Spring Boot 默认不注入以下这些属性，需要自行写配置类
    initialSize: 10
    minIdle: 10
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: false
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，stat:监控统计、log4j：日志记录、wall：防御sql注入
    filters: stat,wall,slf4j
    # 合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: true
    # 打开mergeSql功能；慢SQL记录
    #connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

# mybatis plus 配置
mybatis-plus:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: springboot.druid.mybatisplus.demo.entities
  # 全局配置
  global-config:
    # 0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    # 字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 0
    # 驼峰下划线转换
    db-column-underline: true
    # 刷新mapper 调试神器
    refresh-mapper: true
    # 数据库大写下划线转换
    capital-mode: true
  # 自定义SQL注入器
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true

# 在控制台输出 SQL 语句  
logging:
  level:
    com.wz.springboot.mappers: debug